### ISSUE TITLE
.NET Core EntryPointNotFoundException

### ISSUE THREAD

**Issue by AlexK555** [odalet/Delta.Imaging#2]
When you use reference Delta.Wsq  to .NET core project you get EntryPointNotFoundException: Unable to find an entry point named 'CopyMemory' exception.
It occurred due to some backward compatibility fixes implemented in older versions of .NET framework.

It can be fixed by adding entry point to native methods:

[DllImport("kernel32.dll", EntryPoint = "RtlMoveMemory", ExactSpelling = true)]
public static extern void CopyMemory(IntPtr dest, IntPtr src, IntPtr count);

**Comment by odalet** [comment]
The code in this repository is very old; it's not a surprise things have changed a bit in the last 10+ years. However, I've since moved on to other projects and don't plan on maintaining this any more. However, feel free to forkl and adapt to your needs!
